### ISSUE TITLE
Cannot use "Ctrl+Enter" as Enter in Mac using Karabinar

### ISSUE THREAD

**Issue by GororiK** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#16] opened 2023-06-27 06:36 UTC
Thank you for developing this wonderful extension.
I really appreciate it, but I cannot enter prompts using Ctrl+Enter.
My setting is Mac OS Ventura 13.4, and using Karabinar to modify Caps lock key to Control key. (US keyboard)
Is this situation affecting the function of the extension?

**Comment by masachika-kamada** [comment] 2023-06-27 15:02
Firstly, thank you for using this extension and for your valuable feedback.

We understand the situation you're facing and will be working towards resolving the issue. My co-developer, who uses Mac, will try to replicate the issue based on your report.

To help us with this, if possible, could you please provide us with the following details:

1. Detailed steps to reproduce the issue on Mac OS Ventura 13.4 with Karabiner settings.
2. The key events that are triggered when pressing Ctrl+Enter, as observed using Google Chrome's Developer Tools.

Here are the steps to check key events using the Developer Tools:

1. Open Google Chrome.
2. Right-click on the page and select 'Inspect'.
3. Open the 'Console' tab.
4. Paste the following code into the console and press Enter: 
`document.onkeydown = document.onkeyup = document.onkeypress = function(e){console.log(e);};`
5. Now, each time a key is pressed, the details of the event will be displayed in the console. Please press Ctrl+Enter and share the results with us.

By providing us with this information, we can pursue the cause of the issue more precisely and find an appropriate solution.  

Thank you for your cooperation.

**Comment by GororiK** [comment] 2023-06-27 21:26
Kamada-san, thank you for the kind reply.

I'm not sure other apps except for Karabinar affect this extension, but do not work in my situation.
1. What do you want to know in particular? I'd be happy if you specify the steps.
2. I paste the key events:

KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Enter', code: 'Enter', location: 0, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: false, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Enter', code: 'Enter', location: 0, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: false, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Enter', code: 'Enter', location: 0, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: false, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Enter', code: 'Enter', location: 0, ctrlKey: true, …}
_app-6cb0d68c102a249a.js:14 KeyboardEvent {isTrusted: true, key: 'Control', code: 'ControlRight', location: 2, ctrlKey: false, …}

**Comment by GororiK** [comment] 2023-06-27 21:28
I repeated ctrl+enter several times to record the key events.

**Comment by masachika-kamada** [comment] 2023-06-28 02:14
@GororiK 

Firstly, thank you for providing detailed feedback and key event information. This greatly aids us in identifying the issue.

Upon reviewing our code and considering the information you provided, it seems that this issue could potentially be due to one of the following factors:

1. Other Chrome extensions are causing interference
For instance, we have confirmed that if extensions like [TalkBerry](https://chrome.google.com/webstore/detail/talkberry-talk-to-chatgpt/facjhgcdnbfghhbnmfjgkncnbimfdakb) are installed simultaneously, the submission becomes Enter-based rather than Ctrl + Enter-based. To verify this, please try disabling all other Chrome extensions temporarily and see if the problem is resolved. Alternatively, you could try to see if this extension works on [other supported sites](https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/tree/main#:~:text=https%3A//chat.openai,www.perplexity.ai).

2. The keyboard remapping tool (Karabiner) is causing interference
As a Windows user, I'm not familiar with Karabiner, but I understand that there are various ways to configure the mapping (setting it up yourself, using something someone else has published, etc.). To help my co-developer, who uses a Mac, reproduce the issue, it would be helpful if you could tell us how you set it up. Alternatively, please try disabling Karabiner temporarily and see if the problem is resolved.

Please let us know the results after trying these steps. This will help us to more precisely identify the cause of the issue.

Thank you for your continued cooperation.

**Comment by masachika-kamada** [comment] 2023-07-04 00:16
@GororiK,

I hope this message finds you well. A few days have passed since our last communication and I wanted to follow up on the issue you reported.

Have you had a chance to try the suggested steps? Were they helpful in resolving the issue with the Ctrl + Enter functionality?

If we don't receive a response or if no additional information is provided, we'll assume the issue has been resolved or is no longer relevant. Consequently, we plan to close this issue in a few days.

However, if you encounter this issue again in the future or if you have any other concerns or questions, please don't hesitate to open a new issue. We're here to help!

Best regards,

**Comment by GororiK** [comment] 2023-07-04 00:46
@masachika-kamada 
Sorry for the late reply.
While turning on each disabled extension one by one and checking their functionality, everything worked fine immediately when all of them were enabled. However, afterwards, when the extension"" Web chat GPT (https://chrome.google.com/webstore/detail/webchatgpt-chatgpt-with-i/lpfemeioodjbpieminkklglpmhlngfcn) was turned on, the same situation occurred again. So, it seems that this extension is causing interference.

**Comment by masachika-kamada** [comment] 2023-07-04 01:55
@GororiK,

Thank you for your patience and for taking the time to investigate this issue. Your findings are very helpful.

It seems that the "Web chat GPT" extension is indeed causing interference with our extension. Unfortunately, as developers, we have limited control over how different extensions interact with each other. We recommend keeping the "Web chat GPT" extension disabled when using our extension to avoid this issue.

Your feedback is invaluable to us and we will add this information to the repository's README to help other users who might encounter the same issue.

We appreciate your understanding and cooperation in this matter. Since the cause of the issue has been identified, we will now close this issue. However, if you encounter any other problems or have any questions in the future, please don't hesitate to open a new issue.

Best regards,

**Closed by masachika-kamada** 2023-07-04 01:55 UTC
