### ISSUE TITLE
Not waiting for Ctrl-Enter as of Today

### ISSUE THREAD

**Issue by 8thHalfHour** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#47] opened 2024-05-04 02:23 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
As of today, ChatGPT is back to sending the message when pressing `Enter` instead of requiring `Ctrl-Enter`.

### Steps to reproduce
1. Start a chat with ChatGPT.
2. Press `Enter` to add additional information to the current conversation before sending to the bot.

**Expected behavior** [What you expected to happen.]
I expected the `Enter` button would just create a new line without sending the info to chatbot yet.

**Actual behavior** [What actually happened.]
The chat goes out immediately, unfinished.

**Screenshots**         

### Additional context
MacOS Sonoma v14.4.1
Brave Browser [Version 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (arm64)](https://brave.com/latest/)

**Comment by moykeen** [comment] 2024-05-04 04:56
same for me

**Comment by arakisin** [comment] 2024-05-04 05:20
I am also experiencing the same issue. 
It's a very convenient feature, so I hope for a swift restoration.

**Comment by manota** [comment] 2024-05-04 05:54
same.
please help me.

Windows 10 Pro 22H2
Watefox Browser G6.0.13 (64-bit)

**Comment by masachika-kamada** [comment] 2024-05-04 08:52
@8thHalfHour @moykeen @arakisin @manota 
Thank you all for reporting this issue and providing valuable information. We suspect that the recent change in the ChatGPT URL might be the root cause of this problem. To confirm, can you please verify if the URL you are using is https://chatgpt.com? 

We have already made the necessary changes in the program to accommodate the new URL. However, it takes some time for the updates to reflect on the Chrome Web Store, and we kindly request your patience during this transition period.

If the URL is indeed https://chatgpt.com, then we are confident that the issue will be resolved once the updated extension is available on the Chrome Web Store. In the meantime, we apologize for any inconvenience and appreciate your understanding.

Thank you for your continued support and for bringing this to our attention. We will keep you updated on the progress and let you know once the extension is updated.

**Comment by probablytukars** [comment] 2024-05-04 17:17
I am also experiencing this problem on Firefox. I am using https://chatgpt.com/

**Comment by manota** [comment] 2024-05-04 23:42
@masachika-kamada
I checked that I am using https://chatgpt.com, and the 'ChatGPT Ctrl+Enter Sender' of Firefox addon does not work.
In your comment, you will update it on Chrome web store. If possible, please update it on Firefox.

**Comment by masachika-kamada** [comment] 2024-05-05 06:53
@probablytukars @manota 
We appreciate your understanding regarding the Firefox release. The fix has been completed and submitted for review. It will be reflected on the Firefox Add-ons site once it passes the review process. Thank you for your cooperation.

If you have the time, please consider leaving a positive review for the extension. It would be a great help in our ongoing development efforts.

**Closed** 2024-05-07 00:37 UTC
